### ISSUE TITLE
Call to a member function getIconSet() on null

### ISSUE THREAD

**Issue by GMTeams** [contao-bootstrap/form#33]
Contao 3.5.27
contao-bootstrap/form | 1.1.6
PHP 7.0.28

When I'm trying to login in frontend form, the following error occurs:

```
Fatal error: Uncaught exception Error with message Call to a member function getIconSet() on null thrown in composer/vendor/contao-bootstrap/core/src/Bootstrap.php on line 92
#0 system/modules/bootstrap-core/dca/tl_content.php(68): Netzmacht\Bootstrap\Core\Bootstrap::getIconSet()
#1 system/modules/core/library/Contao/DcaLoader.php(86): include('/home/.sites/30...')
#2 composer/vendor/codefog/contao-haste/library/Haste/Model/Relations.php(515): Contao\DcaLoader->load()
#3 system/modules/core/library/Contao/Database/Installer.php(410): Haste\Model\Relations->addRelationTables(Array)
#4 system/modules/core/library/Contao/DcaExtractor.php(429): Contao\Database\Installer->getFromFile()
#5 system/modules/core/library/Contao/DcaExtractor.php(128): Contao\DcaExtractor->createExtract()
#6 system/modules/core/library/Contao/DcaExtractor.php(144): Contao\DcaExtractor->__construct('tl_page')
#7 system/modules/core/library/Contao/Model/QueryBuilder.php(52): Contao\DcaExtractor::getInstance('tl_page')
#8 system/modules/core/library/Contao/Model.php(1233): Contao\Model\QueryBuilder::find(Array)
#9 system/modules/core/library/Contao/Model.php(1068): Contao\Model::buildFindQuery(Array)
#10 system/modules/core/library/Contao/Model.php(965): Contao\Model::find(Array)
#11 system/modules/core/models/MemberGroupModel.php(136): Contao\Model::findBy(Array, NULL, Array)
#12 system/modules/core/classes/FrontendUser.php(322): Contao\MemberGroupModel::findAllActive()
#13 system/modules/core/library/Contao/User.php(276): Contao\FrontendUser->setUserFromDb()
#14 system/modules/core/classes/FrontendUser.php(156): Contao\User->authenticate()
#15 system/modules/pct_customelements/config/config.php(142): Contao\FrontendUser->authenticate()
#16 system/modules/core/library/Contao/Config.php(141): include('/home/.sites/30...')
#17 system/modules/core/library/Contao/Config.php(108): Contao\Config->initialize()
#18 system/initialize.php(162): Contao\Config::getInstance()
#19 index.php(16): require('/home/.sites/30...')
#20 {main}`
```

**Comment by dmolineus** [comment]
Are there some other 3rd party extensions involved? How is it reproducable?

**Comment by dmolineus** [comment]
Closed because of missing feedback.
